### ISSUE TITLE
start/stop/start sequence not working

### ISSUE THREAD

**Issue by nerk** [jiahansu/GazeJS#1]
The following sequence of steps does not work:
- init()
- start()
- stop()
- start()

Invocation of start() after stop() throws an exception. Reason is that start() checks the status of the tracker and throws 'Illegal status to start tracker' if the status is not INIT.

I tried to modify the start() function as follows:

```
start: function() {
if (this.status === module.exports.INITED || this.status === module.exports.STOPPED) {
            var eventLoopErrorCode = new bridjs.NativeValue.uint32(),
                self = this;
```

Now I get an exception from bridjs:

```
[2015-07-21 09:18:20.019] [INFO] TobiiGazeImpl - OnConnect
C:\Users\thomas.kern\work\webstorm\ww2015-app-polymer1.0\node_modules\gazejs\node_modules\bridjs\lib\bridjs.js:366
                    throw new BridjsException("Buffer was allocated: " + this.
                          ^
Error: Buffer was allocated: undefined
    at _bridjs_impl_update_buffer (C:\Users\thomas.kern\work\webstorm\ww2015-app-polymer1.0\node_modules\gazejs\node_modules\bridjs\lib\bridjs.js:366:27)
    at _bridjs_impl_update_buffer (C:\Users\thomas.kern\work\webstorm\ww2015-app-polymer1.0\node_modules\gazejs\node_modules\bridjs\lib\bridjs.js:312:35)
    at Array.<anonymous> (C:\Users\thomas.kern\work\webstorm\ww2015-app-polymer1.0\node_modules\gazejs\node_modules\bridjs\lib\utils.js:77:34)
    at onDone (C:\Users\thomas.kern\work\webstorm\ww2015-app-polymer1.0\node_modules\gazejs\node_modules\bridjs\lib\function_callback_wrapper.js:61:45)
```

My modification worked for bridjs 1.7.3. I only have this problem with bridjs 2.x.

**Comment by jonathan-reisdorf** [comment]
I have the same issue. I bypassed it by re-creating:
gazejs.createEyeTracker
init
start
stop
gazejs.createEyeTracker
init
start
[...]

Of course that's not actually a solution, but for now it works

**Comment by nerk** [comment]
Thanks, I'll try that as a workaround for now!

**Comment by jiahansu** [comment]
Hi, nerk

BridJS 2.x only support node 0.11.x aor above.
I will check this issue and give solution later

Thanks

**Comment by nerk** [comment]
@jiahansu Yes, I am using BridJS 2.x with node 0.12.7.

**Comment by jiahansu** [comment]
Fixed in V0.5.000-4

**Comment by jonathan-reisdorf** [comment]
nice!

**Comment by nerk** [comment]
Thanks! :+1:

**Comment by jiahansu** [comment]
Hi, all

The calling sequence has some changes, please make sure the onConnect callback is return before you call eyeTracker.start().
