### ISSUE TITLE
GazeJS for EyeLink does'nt work.

### ISSUE THREAD

**Issue by sl0000** [jiahansu/GazeJS#5]
C:\tt>node test
C:\tt\node_modules\gazejs\lib\eyelink\gaze_tracker_impl.js:43
         micro =new eyetypes.MICRO(), hookFunctions = new core_expt.HOOKFCNS2();
                                                      ^

TypeError: core_expt.HOOKFCNS2 is not a constructor
    at Object.<anonymous> (C:\tt\node_modules\gazejs\lib\eyelink\gaze_tracker_impl.js:43:55)
    at runFactory (C:\tt\node_modules\amdefine\amdefine.js:183:30)
    at define (C:\tt\node_modules\amdefine\amdefine.js:277:13)
    at Object.<anonymous> (C:\tt\node_modules\gazejs\lib\eyelink\gaze_tracker_impl.js:37:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)

**Comment by jiahansu** [comment]
It is lastest BirdJS's bug, fixed in v0.5.1-5
